import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  FileText,
  ExternalLink,
  CheckSquare,
  Square,
  Code,
  Sparkles,
  Loader2,
  ArrowRight,
  ArrowUpRight,
  Lock
} from 'lucide-react';
import { getSharedDocument } from '../api.js';

export function ShareView() {
  const { token } = useParams();
  const [docData, setDocData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    async function load() {
      try {
        const data = await getSharedDocument(token);
        setDocData(data);
      } catch (err) {
        setError(err.message || 'Access Denied');
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [token]);

  if (loading) return (
    <div className="flex flex-col h-screen items-center justify-center gap-4 bg-slate-50">
      <Loader2 className="animate-spin text-sky-500" size={48} />
      <p className="text-[10px] font-black uppercase tracking-widest text-slate-400 animate-pulse">Retrieving Asset</p>
    </div>
  );

  if (error || !docData) return (
    <div className="min-h-screen flex items-center justify-center bg-slate-50 p-8">
      <div className="glass p-12 rounded-[3rem] text-center shadow-xl max-w-lg border border-white/20">
        <div className="mx-auto w-16 h-16 bg-rose-50 text-rose-500 rounded-3xl flex items-center justify-center mb-6">
          <Lock className="w-8 h-8" />
        </div>
        <h2 className="text-2xl font-black text-slate-900 mb-2">Access Terminated</h2>
        <p className="font-bold text-slate-500 leading-relaxed">This document is no longer public or the link has expired.</p>
        <Link to="/" className="mt-8 inline-flex items-center gap-2 px-8 py-4 bg-slate-900 text-white rounded-[1.5rem] text-[10px] font-black uppercase tracking-widest hover:bg-black transition-all active:scale-95">
          Create your own <ArrowRight size={14} />
        </Link>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-white">
      {/* Premium Public Header */}
      <nav className="sticky top-0 z-50 w-full glass shadow-sm">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-6">
          <Link to="/" className="flex items-center gap-3 group">
            <div className="h-8 w-1.5 bg-sky-500 rounded-full" />
            <span className="text-xl font-black text-slate-900 tracking-tighter uppercase">BlockNote</span>
          </Link>
          <div className="flex items-center gap-4">
            <div className="hidden sm:flex items-center gap-2 px-4 py-2 rounded-full bg-slate-50 text-[9px] font-black uppercase tracking-widest text-slate-400 border border-slate-100">
              <Sparkles size={12} className="text-sky-500" />
              Published via BlockNote Cloud
            </div>
            <Link
              to="/register"
              className="px-6 py-2.5 bg-slate-900 text-white rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-black transition-all active:scale-95 shadow-lg shadow-black/10"
            >
              Get Started
            </Link>
          </div>
        </div>
      </nav>

      <motion.main
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="mx-auto max-w-4xl px-12 py-24 pb-48"
      >
        <header className="mb-20">
          <h1 className="text-6xl font-black text-slate-900 tracking-tighter mb-8 leading-[1.1]">
            {docData.title}
          </h1>
          <div className="h-2 w-20 bg-sky-500 rounded-full" />
        </header>

        <div className="space-y-4">
          {docData.blocks.map((block) => (
            <div key={block.id} className="py-2">
              <RenderSharedBlock block={block} />
            </div>
          ))}
        </div>

        <footer className="mt-40 pt-10 border-t border-slate-50 text-center">
          <p className="text-[10px] font-black text-slate-400 uppercase tracking-[0.3em] mb-8">Generated by BlockNote Core</p>
          <div className="glass p-10 rounded-[3rem] inline-block max-w-md shadow-xl border border-white/20">
            <h3 className="text-xl font-black text-slate-900 mb-2">Build your own workspace</h3>
            <p className="text-slate-500 font-medium mb-8">Join thousands of professionals creating beautiful documents every day.</p>
            <Link to="/register" className="inline-flex items-center gap-3 px-10 py-5 bg-sky-500 text-white rounded-[2rem] text-xs font-black uppercase tracking-widest hover:bg-sky-600 transition-all active:scale-95 shadow-xl shadow-sky-500/20">
              Claim your account <ExternalLink size={16} />
            </Link>
          </div>
        </footer>
      </motion.main>
    </div>
  );
}

function RenderSharedBlock({ block }) {
  switch (block.type) {
    case 'heading_1':
      return <h1 className="text-5xl font-black text-slate-900 tracking-tighter leading-tight">{block.content?.text || ''}</h1>;
    case 'heading_2':
      return <h2 className="text-3xl font-black text-slate-800 tracking-tight">{block.content?.text || ''}</h2>;
    case 'todo':
      return (
        <div className="flex items-start gap-4">
          <div className={`mt-1.5 ${block.content?.checked ? 'text-sky-500' : 'text-slate-200'}`}>
            {block.content?.checked ? <CheckSquare size={22} className="fill-sky-50" /> : <Square size={22} />}
          </div>
          <p className={`text-xl font-medium leading-relaxed ${block.content?.checked ? 'text-slate-300 line-through decoration-slate-200 decoration-2' : 'text-slate-600'}`}>
            {block.content?.text || ''}
          </p>
        </div>
      );
    case 'code':
      return (
        <div className="rounded-[2rem] bg-slate-900 p-8 font-mono text-[14px] text-sky-400 shadow-2xl relative border border-slate-800 my-6">
          <pre className="whitespace-pre-wrap leading-relaxed">{block.content?.text || ''}</pre>
          <div className="absolute right-8 top-8 text-slate-700">
            <Code size={16} />
          </div>
        </div>
      );
    case 'divider':
      return <div className="py-8"><div className="h-1 bg-slate-50 w-full rounded-full" /></div>;
    case 'image':
      return block.content?.url ? (
        <img src={block.content.url} alt="Shared asset" className="mx-auto rounded-[2rem] max-h-[600px] shadow-2xl my-8" />
      ) : null;
    default:
      return <p className="text-2xl leading-relaxed text-slate-600 font-medium">{block.content?.text || ''}</p>;
  }
}
